services:
  flask_app:
    build: ./app
    container_name: techsecure_flask
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
      - .env.local
    networks:
      - techsecure_net
    depends_on:
      - db_mysql

  db_mysql:
    image: mysql:8.0
    container_name: techsecure_db
    restart: always
    env_file:
      - .env
      - .env.local
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - techsecure_net

  adminer:
    image: adminer:latest
    container_name: techsecure_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - techsecure_net
    depends_on:
      - db_mysql

volumes:
  db_data:

networks:
  techsecure_net:
    driver: bridge